### ISSUE TITLE
Hole in the segmentation v2

### ISSUE THREAD

**Issue by rbumm** [wasserth/TotalSegmentator#194]
When using TotalSegmentator 2.0.3 from the upcoming Slicer extension v2, I get

![image](https://github.com/wasserth/TotalSegmentator/assets/18140094/49f1a0bc-b1fb-45ab-a7d6-9023be081ca6)

with the CTChest demo dataset. 

Task: "total". 

Any ideas ?

**Comment by wasserth** [comment]
Very strange. Is this using the `--fast` option? And how can I access the CTChest demo dataset? Best would be as nifti file.

**Comment by rbumm** [comment]
Here is a Google drive folder link. 

https://drive.google.com/drive/folders/1Cy9JWeVS7bb6H4EoqtOYgbd9mHH3pfQQ?usp=sharing

**Comment by marco900000** [comment]
Hi @wasserth we are having the same problem when using the fast option

**Comment by costanzasimoncini** [comment]
Hello, we are having a very similar issue using CT scans of patients in standard position (supine) or rotated. We are using the `-f -ml` options 
<img width="490" alt="holeCT" src="https://github.com/wasserth/TotalSegmentator/assets/52277952/1c0760d6-ca9c-42fd-a0b7-dec73e6b79e2">

**Comment by wasserth** [comment]
I can confirm there is a major bug in the fast mode. It does not happen if you run without `fast`. I am currently trying to resolve it. This will take a few days since I have to retrain the `fast` model.

**Comment by dulicui742** [comment]
I have the same problem!
task = "total"  --fast False
<img width="182" alt="pred" src="https://github.com/wasserth/TotalSegmentator/assets/77182160/94f7c354-189c-4fdc-af76-23ea9d8891ee">

Any ideas ?

**Comment by wasserth** [comment]
I just released a new version 2.0.4 which should solve this problem.

**Comment by rbumm** [comment]
Without fast within Slicer TS 2.0.4: 

![image](https://github.com/wasserth/TotalSegmentator/assets/18140094/edd8ff70-c8f3-43fb-8289-2b82a111047c)

**Comment by dulicui742** [comment]
> I just released a new version 2.0.4 which should solve this problem.

I am sorry, but I don't use the weight 297.
config:  task = "total" without fast option

**Comment by lassoan** [comment]
Unfortunately, the problem is still the same with `Dataset297_TotalSegmentator_total_3mm_1559subj_v204` (for the same CTChest input image that Rudolf tested before):

![image](https://github.com/wasserth/TotalSegmentator/assets/307929/69c3f162-0149-46c1-b5e2-e67f959c14a7)

Here are the SHA256 hashes for the model files, so that you can check that we have the correct files:

```
e804e08ad8912e3a6f541741c8c78799d75acbd3f4f3f18ff5f211bbd3da961a *dataset.json
f1336cd0df44e0eeecfa69143226c05b246c550e690b7b12929f65ca9843260f *dataset_fingerprint.json
56a77544a7a1523f33ec21cc6060b68855ad73f351c764c0d62c3b25761610b0 *plans.json
54d7634ce6294da418b4eb2a23b3fe55bc3821d1c6856a007156a439dd2e6b83 *fold_0\checkpoint_final.pth
4ed8590e29d97c60d37ac733fdda88134d9da3a33e98a70f4b7e12118b43d9b4 *fold_0\debug.json
150f9449edb8de72513a6eaf634e474408ef75e32d8a2485b7d557f6c37e4c7a *fold_0\progress.png
```

**Comment by wasserth** [comment]
Thanks for the PR. That fixed the download issue.
I also (hopefully) figured out the reason for the holes in the segmentations. Something got broken in the new nnunet version (2.2). When I downgrade to 2.1 it seems to work fine again. Then I can also use the original weights/models.
I just published a new version on pypi (TotalSegmentator 2.0.5). I hope this solves the issues.

**Comment by rbumm** [comment]
I have integrated 2.0.5 install into the 3D Slicer extension (forked newly
from Andras) but get error messages:

Processing started

Writing input file to
C:/Users/Rudolf/AppData/Local/Temp/Slicer/__SlicerTemp__2023-10-20_15+17+00.790/total-segmentator-input.nii

Creating segmentations with TotalSegmentator AI...

Total Segmentator arguments: ['-i',
'C:/Users/Rudolf/AppData/Local/Temp/Slicer/__SlicerTemp__2023-10-20_15+17+00.790/total-segmentator-input.nii',
'-o',
'C:/Users/Rudolf/AppData/Local/Temp/Slicer/__SlicerTemp__2023-10-20_15+17+00.790/segmentation',
'--ml', '--task', 'total', '--fast']

Traceback (most recent call last):

File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer
5.4.0_2\lib\Python\Lib\runpy.py", line 197, in _run_module_as_main

return _run_code(code, main_globals, None,

File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer
5.4.0_2\lib\Python\Lib\runpy.py", line 87, in _run_code

exec(code, run_globals)

File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer
5.4.0_2\lib\Python\Scripts\TotalSegmentator.exe\__main__.py", line 7, in
<module>

File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer
5.4.0_2\lib\Python\Lib\site-packages\totalsegmentator\bin\TotalSegmentator.py",
line 127, in main

totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp,
args.nr_thr_saving,

File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer
5.4.0_2\lib\Python\Lib\site-packages\totalsegmentator\python_api.py", line
77, in totalsegmentator

from totalsegmentator.nnunet import nnUNet_predict_image # this has to be
after setting new env vars

File "C:\Users\Rudolf\AppData\Local\slicer.org\Slicer
5.4.0_2\lib\Python\Lib\site-packages\totalsegmentator\nnunet.py", line 23,
in <module>

from nnunetv2.inference.predict_from_raw_data import predict_from_raw_data

ImportError: cannot import name 'predict_from_raw_data' from
'nnunetv2.inference.predict_from_raw_data' (C:\Users\Rudolf\AppData\Local\
slicer.org\Slicer
5.4.0_2\lib\Python\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py)

Exception ignored in: <totalsegmentator.libs.DummyFile object at
0x000002AA56F228E0>

AttributeError: 'DummyFile' object has no attribute 'flush'

Am Fr., 20. Okt. 2023 um 11:25 Uhr schrieb Jakob Wasserthal <
***@***.***>:

**Comment by lassoan** [comment]
Sorry, I think this latest issue (`...cannot import name...`) is our fault (a problem in the Slicer extension, see https://github.com/lassoan/SlicerTotalSegmentator/pull/39#issuecomment-1772752630). We'll fix it and get back to you with the result soon.

**Comment by lassoan** [comment]
I confirm that the issue is fixed in TotalSegmentator 2.0.5.

**Comment by rbumm** [comment]
Yes, the issue is fixed.

Am Sa., 21. Okt. 2023 um 03:34 Uhr schrieb Andras Lasso <
***@***.***>:

**Comment by wasserth** [comment]
Great!
